Add Export & Import release bundle docs
jfrog/documentation pull request #107
Opened 2024-03-25 08:51 UTC by EyalDelarea

2024-03-25 09:26 UTC, eyalbe4 reviewed
I suggest also explaining the use case of importing and exporting a release bundle.

2024-04-07 13:26 UTC, RobiNino requested changes
Looks good! Please only merge after the import command is released

2024-04-07 13:26 UTC, RobiNino commented on jfrog-applications/jfrog-cli/cli-for-jfrog-artifactory/release-lifecycle-management.md
> +| target pattern         | Specifies the local file system target download path
I suggest to put the whole explanation as in the help because users might relay on documentation and not the help command

2024-04-07 13:26 UTC, RobiNino commented on jfrog-applications/jfrog-cli/cli-for-jfrog-artifactory/release-lifecycle-management.md
> +| target pattern         | Specifies the local file system target download path
Same comment for `mapping-pattern` and `mapping-target`.

Also, missing `split-count` and `min-split`

2024-04-07 13:26 UTC, RobiNino commented on jfrog-applications/jfrog-cli/cli-for-jfrog-artifactory/release-lifecycle-management.md
> +## Importing Release Bundle Archive
```suggestion
## Importing a Release Bundle archive
```

2024-04-07 13:26 UTC, RobiNino commented on jfrog-applications/jfrog-cli/cli-for-jfrog-artifactory/release-lifecycle-management.md
> +Please note this functionality only works on Edge nodes within an Air Gap environment.
Isn't the only constraint is being an Edge node (defined by license)?
```suggestion
Please note this functionality only works on Edge nodes within an air-gapped environment.
```

2024-04-07 13:26 UTC, RobiNino commented on jfrog-applications/jfrog-cli/cli-for-jfrog-artifactory/release-lifecycle-management.md
> +| path to archive        | path to the release bundle archive on the filesystem                             |
```suggestion
| path to archive        | Path to the release bundle archive on the filesystem                             | 
```

2024-04-07 13:26 UTC, RobiNino commented on jfrog-applications/jfrog-cli/cli-for-jfrog-artifactory/release-lifecycle-management.md
> +Export release bundle named "myExportedApp" and version 1.0.0
```suggestion
Import a Release Bundle named "myExportedApp" and version 1.0.0
```

2024-04-17 08:33 UTC, merged