Add worker-cli documentation
jfrog/documentation pull request #139
Opened 2024-07-03 14:53 UTC by ehl-jf

2024-07-15 16:22 UTC, RemiBou commented on jfrog-applications/jfrog-cli/cli-for-jfrog-platform-services/README.md
> +**Managing platform Workers**
remove "platform"

2024-07-15 16:22 UTC, RemiBou commented on jfrog-applications/jfrog-cli/cli-for-jfrog-platform-services/platform-workers-add-secret.md
> +# Initialize a Worker
title is not correct

2024-07-15 16:22 UTC, RemiBou commented on jfrog-applications/jfrog-cli/cli-for-jfrog-platform-services/platform-workers-deploy.md
> +# Initialize a Worker
same title error

2024-07-15 16:22 UTC, RemiBou commented on jfrog-applications/jfrog-cli/cli-for-jfrog-platform-services/platform-workers-deploy.md
> +This command is used to Deploy a worker.
lower case, "deploy". Maybe say "This command is used to update the worker definition (code, description , filter, secret ...) on your Artifactory instance

2024-07-15 16:22 UTC, RemiBou commented on jfrog-applications/jfrog-cli/cli-for-jfrog-platform-services/platform-workers-execute.md
> +# Execute a manual worker
Align, either "manual" or "generic"

2024-07-15 16:22 UTC, RemiBou commented on jfrog-applications/jfrog-cli/cli-for-jfrog-platform-services/platform-workers-dry-run.md
> +Dry run a worker. The worker needs to be initialized before running this command.
add link to init. I think this statement is true for most of the commands, please add it to all command where it's needed

2024-07-15 16:22 UTC, RemiBou commented on jfrog-applications/jfrog-cli/cli-for-jfrog-platform-services/platform-workers-init.md
> +This command is used to initialize a new platform worker.
be more descriptive like "This command will create all necessary file in the current directory in order to start writing your worker : sample code, manifest file and sample tests" something like that

2024-07-15 16:22 UTC, RemiBou commented on jfrog-applications/jfrog-cli/cli-for-jfrog-platform-services/platform-workers-list-event.md
> +# Initialize a Worker
title

2024-07-15 16:22 UTC, RemiBou commented on jfrog-applications/jfrog-cli/cli-for-jfrog-platform-services/platform-workers-list-event.md
> +This command list all the available events for a given server.
"on your Artifactory"

2024-07-15 16:22 UTC, RemiBou commented on jfrog-applications/jfrog-cli/cli-for-jfrog-platform-services/platform-workers-list.md
> +List workers. The default output is a CSV format with columns `name`,`action`,`description`,`enabled`.
List workers saved on your Artifactory instance.

2024-07-15 16:22 UTC, RemiBou commented on jfrog-applications/jfrog-cli/cli-for-jfrog-platform-services/platform-workers-undeploy.md
> +This command is used to initialize a new platform worker.
comment is bad

2024-07-15 16:22 UTC, RemiBou commented on jfrog-applications/jfrog-cli/cli-for-jfrog-platform-services/platform-workers-undeploy.md
> +# Initialize a Worker
title

2024-08-12 13:48 UTC, merged

2024-08-12 13:51 UTC, eyalbe4 requested changes

2024-08-12 13:51 UTC, eyalbe4 commented on jfrog-applications/jfrog-cli/cli-for-jfrog-platform-services/platform-workers-add-secret.md
> +jfrog worker add-secret my-secret
Non of the existing examples in the JFrog CLI documentation use the `jfrog` executable. To maintain consistency and avoid confusion, you should the `jf` executable all across.

2024-08-12 13:51 UTC, eyalbe4 commented on jfrog-applications/jfrog-cli/cli-for-jfrog-platform-services/README.md
> +This page describes how to use JFrog CLI with JFrog Platform Services.
I'm not sure that the term "Platform Services" would be clear for the user. You can consult with s technical writer about the best introductory phrasing. 
There's a chance some of the phrasing throughout this PR can be further improved.